server:
  port: 8090

client:
  timeout: 10000

bot:

  # WebSocket real-time feed, Products Channel host
  subscription:
    protocol: https:// #wss://
    host: localhost:8080 #rtf.beta.getbux.com
    token: eyJhbGciOiJIUzI1NiJ9.eyJyZWZyZXNoYWJsZSI6ZmFsc2UsInN1YiI6ImJiMGNkYTJiLWExMGUtNGVkMy1hZDVhLTBmODJiNGMxNTJjNCIsImF1ZCI6ImJldGEuZ2V0YnV4LmNvbSIsInNjcCI6WyJhcHA6bG9naW4iLCJydGY6bG9naW4iXSwiZXhwIjoxODIwODQ5Mjc5LCJpYXQiOjE1MDU0ODkyNzksImp0aSI6ImI3MzlmYjgwLTM1NzUtNGIwMS04NzUxLTMzZDFhNGRjOGY5MiIsImNpZCI6Ijg0NzM2MjI5MzkifQ.M5oANIi2nBtSfIfhyUMqJnex-JYg6Sm92KPYaUL9GKg

  trade:
    protocol: http:// #https://
    host: localhost:8080 #api.beta.getbux.com
    token: eyJhbGciOiJIUzI1NiJ9.eyJyZWZyZXNoYWJsZSI6ZmFsc2UsInN1YiI6ImJiMGNkYTJiLWExMGUtNGVkMy1hZDVhLTBmODJiNGMxNTJjNCIsImF1ZCI6ImJldGEuZ2V0YnV4LmNvbSIsInNjcCI6WyJhcHA6bG9naW4iLCJydGY6bG9naW4iXSwiZXhwIjoxODIwODQ5Mjc5LCJpYXQiOjE1MDU0ODkyNzksImp0aSI6ImI3MzlmYjgwLTM1NzUtNGIwMS04NzUxLTMzZDFhNGRjOGY5MiIsImNpZCI6Ijg0NzM2MjI5MzkifQ.M5oANIi2nBtSfIfhyUMqJnex-JYg6Sm92KPYaUL9GKg
    # The delta gap between buy Data when we allow to buy
    buy-delta: 1000
    # The delta gap between buy Data when we allow to sell
    sell-delta: 1000

  products:
    -
      product-id: sb26493
      buy-price: 12577.3
      upper-limit: 14000.3
      lower-limit: 10000.3

    -
      product-id: sb26496
      buy-price: 1577.3
      upper-limit: 3000.3
      lower-limit: 1000.3
